@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

    class "**Patient**" as P<<TM>> {
        |_ identifier 1..*
          |_ niss 0..1
          |_ otherId 0..1
          |_ usernName 0..1   
          |_ otherId 0..1
        |_ name
        |_ userEmail 0..1
        |_ dateOfBirth 0..1  
    }



    class "**Measurement**" as Meas<<TM>> {
            |_ identifier 1..*
            |_ status 1..1
            |_ category 1..*
            |_ code 0..1  
            |_ timeStamp
            |_ period
            |_ value 0..1
            |_ referenceRange 0..1    
              |_ interval 0..1
              |_ normalValue 0..1
              |_ type 0..1
              |_ age 0..1
              |_ text 0..1
            |_ interpretation  1..*
            |_ derivedFrom  1..*
    }

    class "**Component**" as C<<TM>> {
              |_ value 0..1
              |_ dataAbsentReason  0..*   
              |_ interpretation  0..*
              |_ referenceRange 0..1
                |_ interval 0..1
                |_ normalValue 0..1
                |_ type 0..1
                |_ age 0..1
                |_ note 0..1
              |_ note 1..*
    }

    class "**Report**" as R<<TM>> {
        |_ identifier 1..*  
        |_ status 1..1
        |_ type 0..1  
        |_ date 1..1
        |_ author 1..*
        |_ title 1..1
    }

    class "**Device**" as D<<TM>> {
          |_ model 1..*
          |_ serialNumber 0..1    
          |_ manufacturer 0..*  
          |_ note 0..* 
    }

    class "**Software**" as SW<<TM>> {
          |_ softwareName 1..*   
          |_ version 0..1
          |_ manufacturer 0..* 
          |_ note 0..*
    }


P -r- R: "                    "
P -d- Meas : " "
R -- Meas 
'R -d[hidden]- C : " "

D -r[hidden]- SW: "                  "

Meas o-r- C: "           "

C -u-o C


Meas -d- D
Meas -r- SW
C -r- D
C -r- SW


@enduml