@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


package "FHIR Base" as F {
    class "**FHIR Observation**" as FO<<TM>> {
        |_ identifier 1..*
        --
    }
    ' class "**FHIR Patient**" as FP<<TM>> {
    '     |_ identifier 1..*
    '     --
    ' }
}

package "BE Base" as BE {
    ' class "**BE Patient**" as BEP<<TM>> {
    '     |_ identifier 1..*
    '     --
    ' }
    class "**BE Observation**" as BEO<<TM>> {
        |_ identifier 1..*
        --
    }
}

package "Monitoring" as M {
    ' class "**[BE] Patient Monitoring Patient**" as MP<<TM>> {
    '     |_ identifier 1..*
    '     --
    ' }
    class "**[BE] Patient Monitoring Observation**" as MO<<TM>> {
        |_ identifier 1..*
        --
    }
}

package "Vendor 2  " as FC {
  class "**FC Observation**" as FCO<<TM>> {
      |_ identifier 1..*
      --
  }
'   class "**ValueSet**" as FVS<<TM>> {
'       |_ identifier 1..*
'       --
'   }
 }

package "Vendor 1  " as BF {
  class "**BF Observation**" as BFO<<TM>> {
      |_ identifier 1..*
      --
  }
'   class "**ValueSet**" as BFVS<<TM>> {
'       |_ identifier 1..*
'       --
'   }


}


'FP <|-u- BEP'
'BEP .u. MP
FO <|-u- BEO
BEO .u. MO

FO <|-u- MO
'MP <|-u- HRP
'FP <|-u- MP
MO <|-u- FCO
MO <|-u- BFO
'FO -r[hidden]- FP: "         " 

'FCO -l[hidden]- FVS
'BFO -r[hidden]- BFVS


@enduml